### ISSUE TITLE
🐛 Bug: Hydration issues in the template between server/client

### ISSUE THREAD

**Issue by seriouslysean** [philly-js-club/philly-js-club-website#22]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Server and client markup should match.

### Actual

```
react-dom.development.js:86 Warning: Expected server HTML to contain a matching <meta> in <head>.
    at meta
    at head
    at html
    at App
    at RemixRoute (http://localhost:3000/build/_shared/chunk-F46RCTUY.js:4399:3)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-F46RCTUY.js:2743:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-F46RCTUY.js:3126:9)
    at Routes (http://localhost:3000/build/_shared/chunk-F46RCTUY.js:2997:5)
    at Router (http://localhost:3000/build/_shared/chunk-F46RCTUY.js:2944:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-F46RCTUY.js:2893:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-F46RCTUY.js:4018:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-F46RCTUY.js:5460:55)
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnForInsertedHydratedElement @ react-dom.development.js:10499
didNotFindHydratableInstance @ react-dom.development.js:11458
warnNonhydratedInstance @ react-dom.development.js:12385
tryToClaimNextHydratableInstance @ react-dom.development.js:12534
updateHostComponent @ react-dom.development.js:19902
beginWork @ react-dom.development.js:21618
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

### Additional Info

Run the app via `pnpm dev` and load http://localhost:3000/ then check the console.

**Comment by JoshuaKGoldberg** [comment]
🤔 works on my machine. I tried `rm -rf node_modules .cache; pnpm i; pnpm dev` and still none. Weird!

@seriouslysean where are those errors showing up? Looks like the browser console? 

Also, what system specs are you running with? I'm:

* macOS Ventura 13.2
* Chrome 112
* Node 18.7.0

I wonder if this is a just-you thing, a just-me thing, or a some-people-but-not-others... 🙃

**Comment by seriouslysean** [comment]
If you're not seeing it, I think we're safe to close this and chalk it up to a me thing.
